volumes:
  database:

services:
  mariadb:
    image: mariadb
    container_name: rltm-mariadb
    restart: always
    env_file: .env
    volumes:
      - database:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306/tcp

  rltm:
    build: .
    image: rltm
    container_name: rltm
    restart: unless-stopped
    depends_on:
      - mariadb
